# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(839, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 50, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 50, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 50, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 310, 55, 16))
        self.label_11.setObjectName("label_11")
        self.output = QtWidgets.QTextBrowser(self.centralwidget)
        self.output.setEnabled(True)
        self.output.setGeometry(QtCore.QRect(100, 300, 221, 41))
        self.output.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.output.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.output.setOverwriteMode(False)
        self.output.setTabStopDistance(80.0)
        self.output.setAcceptRichText(True)
        self.output.setPlaceholderText("")
        self.output.setObjectName("output")
        self.button_ok = QtWidgets.QPushButton(self.centralwidget)
        self.button_ok.setGeometry(QtCore.QRect(470, 300, 93, 41))
        self.button_ok.setObjectName("button_ok")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(590, 300, 93, 41))
        self.button_clear.setObjectName("button_clear")
        self.button_quit = QtWidgets.QPushButton(self.centralwidget)
        self.button_quit.setGeometry(QtCore.QRect(710, 300, 93, 41))
        self.button_quit.setObjectName("button_quit")
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_1.setGeometry(QtCore.QRect(100, 90, 62, 22))
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(180, 90, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(260, 90, 62, 22))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(260, 130, 62, 22))
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(180, 130, 62, 22))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(100, 130, 62, 22))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(500, 50, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(600, 50, 55, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(470, 90, 31, 16))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(470, 120, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(470, 150, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(470, 180, 31, 16))
        self.label_14.setObjectName("label_14")
        self.rightSpinBox_1 = QtWidgets.QSpinBox(self.centralwidget)
        self.rightSpinBox_1.setGeometry(QtCore.QRect(500, 90, 61, 21))
        self.rightSpinBox_1.setObjectName("rightSpinBox_1")
        self.rightDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rightDoubleSpinBox_1.setGeometry(QtCore.QRect(500, 120, 62, 22))
        self.rightDoubleSpinBox_1.setObjectName("rightDoubleSpinBox_1")
        self.R_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.R_1.setEnabled(True)
        self.R_1.setGeometry(QtCore.QRect(500, 150, 61, 21))
        self.R_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.R_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.R_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.R_1.setOverwriteMode(False)
        self.R_1.setTabStopDistance(80.0)
        self.R_1.setAcceptRichText(True)
        self.R_1.setPlaceholderText("")
        self.R_1.setObjectName("R_1")
        self.N_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.N_1.setEnabled(True)
        self.N_1.setGeometry(QtCore.QRect(500, 180, 61, 21))
        self.N_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.N_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.N_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.N_1.setOverwriteMode(False)
        self.N_1.setTabStopDistance(80.0)
        self.N_1.setAcceptRichText(True)
        self.N_1.setPlaceholderText("")
        self.N_1.setObjectName("N_1")
        self.N_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.N_2.setEnabled(True)
        self.N_2.setGeometry(QtCore.QRect(600, 180, 61, 21))
        self.N_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.N_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.N_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.N_2.setOverwriteMode(False)
        self.N_2.setTabStopDistance(80.0)
        self.N_2.setAcceptRichText(True)
        self.N_2.setPlaceholderText("")
        self.N_2.setObjectName("N_2")
        self.R_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.R_2.setEnabled(True)
        self.R_2.setGeometry(QtCore.QRect(600, 150, 61, 21))
        self.R_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.R_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.R_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.R_2.setOverwriteMode(False)
        self.R_2.setTabStopDistance(80.0)
        self.R_2.setAcceptRichText(True)
        self.R_2.setPlaceholderText("")
        self.R_2.setObjectName("R_2")
        self.rightSpinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.rightSpinBox_2.setGeometry(QtCore.QRect(600, 90, 61, 21))
        self.rightSpinBox_2.setObjectName("rightSpinBox_2")
        self.rightDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rightDoubleSpinBox_2.setGeometry(QtCore.QRect(600, 120, 62, 22))
        self.rightDoubleSpinBox_2.setObjectName("rightDoubleSpinBox_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 55, 16))
        self.label_4.setObjectName("label_4")
        self.W_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.W_1.setEnabled(True)
        self.W_1.setGeometry(QtCore.QRect(100, 170, 51, 21))
        self.W_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.W_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_1.setOverwriteMode(False)
        self.W_1.setTabStopDistance(80.0)
        self.W_1.setAcceptRichText(True)
        self.W_1.setPlaceholderText("")
        self.W_1.setObjectName("W_1")
        self.W_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.W_2.setEnabled(True)
        self.W_2.setGeometry(QtCore.QRect(180, 170, 51, 21))
        self.W_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.W_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_2.setOverwriteMode(False)
        self.W_2.setTabStopDistance(80.0)
        self.W_2.setAcceptRichText(True)
        self.W_2.setPlaceholderText("")
        self.W_2.setObjectName("W_2")
        self.W_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.W_3.setEnabled(True)
        self.W_3.setGeometry(QtCore.QRect(260, 170, 51, 21))
        self.W_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.W_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.W_3.setOverwriteMode(False)
        self.W_3.setTabStopDistance(80.0)
        self.W_3.setAcceptRichText(True)
        self.W_3.setPlaceholderText("")
        self.W_3.setObjectName("W_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Z1"))
        self.label_2.setText(_translate("MainWindow", "Z2"))
        self.label_3.setText(_translate("MainWindow", "Z3"))
        self.label_6.setText(_translate("MainWindow", "Э1"))
        self.label_7.setText(_translate("MainWindow", "Э2"))
        self.label_11.setText(_translate("MainWindow", "Ответ"))
        self.button_ok.setText(_translate("MainWindow", "Ок"))
        self.button_clear.setText(_translate("MainWindow", "Сброс"))
        self.button_quit.setText(_translate("MainWindow", "Выход"))
        self.label_8.setText(_translate("MainWindow", "Э1"))
        self.label_9.setText(_translate("MainWindow", "Э2"))
        self.label_10.setText(_translate("MainWindow", "Ri"))
        self.label_12.setText(_translate("MainWindow", "Ra"))
        self.label_13.setText(_translate("MainWindow", "R"))
        self.label_14.setText(_translate("MainWindow", "N"))
        self.label_4.setText(_translate("MainWindow", "W"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
